config/routes.rb
JackAppBase::Application.routes.draw do
  resources :answers

  resources :indicators

  resources :surveys

  resources :sectors

  resources :sites

  resources :regions

  resources :sources

  devise_for :users

  root :to => 'statics#home'

end

app/models/sector.rb
class Sector < ActiveRecord::Base
  attr_accessible :name

  has_many :sources

  validates :name, :presence => true, :uniqueness => true

end

app/controllers/sectors_controller.rb
class SectorsController < ApplicationController
  load_and_authorize_resource

  # GET /sectors
  # GET /sectors.json
  def index
    @sectors = Sector.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sectors }
    end
  end

  # GET /sectors/1
  # GET /sectors/1.json
  def show
    @sector = Sector.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sector }
    end
  end

  # GET /sectors/new
  # GET /sectors/new.json
  def new
    @sector = Sector.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sector }
    end
  end

  # GET /sectors/1/edit
  def edit
    @sector = Sector.find(params[:id])
  end

  # POST /sectors
  # POST /sectors.json
  def create
    @sector = Sector.new(params[:sector])

    respond_to do |format|
      if @sector.save
        format.html { redirect_to @sector, notice: 'Sector was successfully created.' }
        format.json { render json: @sector, status: :created, location: @sector }
      else
        format.html { render action: "new" }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sectors/1
  # PUT /sectors/1.json
  def update
    @sector = Sector.find(params[:id])

    respond_to do |format|
      if @sector.update_attributes(params[:sector])
        format.html { redirect_to @sector, notice: 'Sector was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sectors/1
  # DELETE /sectors/1.json
  def destroy
    @sector = Sector.find(params[:id])
    @sector.destroy

    respond_to do |format|
      format.html { redirect_to sectors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/views/sectors/_form.html.haml
= bootstrap_form_for @sector do |f|
  = f.text_field :name, :class => 'span4'
  = f.actions

app/views/sectors/edit.html.haml
%h1 Editing sector

= render 'form'

= link_to 'Show', @sector
\|
= link_to 'Back', sectors_path

app/views/sectors/index.html.haml
.container-fluid
  .row-fluid
    .span12
      %h1 Listing sectors

      %table.table.table-striped.table-condensed
        %tr
          %th Name
          %th
          %th
          %th

        - @sectors.each do |sector|
          %tr
            %td= sector.name
            %td= link_to 'Show', sector
            %td= link_to 'Edit', edit_sector_path(sector)
            %td= link_to 'Destroy', sector, :confirm => 'Are you sure?', :method => :delete

      %br

      = link_to 'New Sector', new_sector_path

app/views/sectors/new.html.haml
.container
  .row
    .span4.offset4
      %h1 New sector

      = render 'form'

      = link_to 'Back', sectors_path

app/views/sectors/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @sector.name

= link_to 'Edit', edit_sector_path(@sector)
\|
= link_to 'Back', sectors_path