config/routes.rb
JackAppBase::Application.routes.draw do
  resources :answers

  resources :indicators

  resources :surveys

  resources :sectors

  resources :sites

  resources :regions

  resources :sources

  devise_for :users

  root :to => 'statics#home'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :content, :indicator_id

  belongs_to :question

  validates :content, :presence => true, :uniqueness => { :scope => :indicator_id, :message => 'Answers must be unique per indicator' }

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  load_and_authorize_resource

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @answers }
    end
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    @answer = Answer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/new
  # GET /answers/new.json
  def new
    @answer = Answer.new(params[:answer])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @answer }
      format.js
    end
  end

  # GET /answers/1/edit
  def edit
    @answer = Answer.find(params[:id])
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(params[:answer])

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render json: @answer, status: :created, location: @answer }
      else
        format.html { render action: "new" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /answers/1
  # PUT /answers/1.json
  def update
    @answer = Answer.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :no_content }
      format.js
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_fields.html.haml
= f.text_field :content, :label => 'Answer'

app/views/answers/_form.html.haml
= form_for @answer do |f|
  -if @answer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@answer.errors.count, "error")} prohibited this answer from being saved:"
      %ul
        - @answer.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :indicator_id
    = f.number_field :indicator_id
  .field
    = f.label :content
    = f.text_field :content
  .actions
    = f.submit 'Save'

app/views/answers/destroy.js.erb
$(function(){
  $('#answer<%= params[:id] %>').remove();
});

app/views/answers/edit.html.haml
%h1 Editing answer

= render 'form'

= link_to 'Show', @answer
\|
= link_to 'Back', answers_path

app/views/answers/index.html.haml
%h1 Listing answers

%table
  %tr
    %th Indicator
    %th Content
    %th
    %th
    %th

  - @answers.each do |answer|
    %tr
      %td= answer.indicator_id
      %td= answer.content
      %td= link_to 'Show', answer
      %td= link_to 'Edit', edit_answer_path(answer)
      %td= link_to 'Destroy', answer, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Answer', new_answer_path

app/views/answers/new.html.haml
%h1 New answer

= render 'form'

= link_to 'Back', answers_path

app/views/answers/new.js.erb
$(function(){
  $('#indicator<%= params[:indicator_id] %>').find('.control-group').last().after('<input type="text" name="survey[indicators_attributes][0][answers_attributes][0][content]">')
});

app/views/answers/show.html.haml
%p#notice= notice

%p
  %b Indicator:
  = @answer.indicator_id
%p
  %b Content:
  = @answer.content

= link_to 'Edit', edit_answer_path(@answer)
\|
= link_to 'Back', answers_path