config/routes.rb
JackAppBase::Application.routes.draw do
  resources :answers

  resources :indicators

  resources :surveys

  resources :sectors

  resources :sites

  resources :regions

  resources :sources

  devise_for :users

  root :to => 'statics#home'

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  attr_accessible :name, :indicators_attributes

  has_many :indicators, :dependent => :destroy

  accepts_nested_attributes_for :indicators, :reject_if => proc { |a| a['name'].blank? }, :allow_destroy => true

  validates :name, :presence => true, :uniqueness => true

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  load_and_authorize_resource

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @surveys }
    end
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
    @survey = Survey.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @survey }
    end
  end

  # GET /surveys/new
  # GET /surveys/new.json
  def new
    @survey = Survey.new
    3.times do
      indicator = @survey.indicators.build
      4.times { indicator.answers.build }
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @survey }
    end
  end

  # GET /surveys/1/edit
  def edit
    @survey = Survey.find(params[:id])
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(params[:survey])

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render json: @survey, status: :created, location: @survey }
      else
        format.html { render action: "new" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /surveys/1
  # PUT /surveys/1.json
  def update
    @survey = Survey.find(params[:id])

    respond_to do |format|
      if @survey.update_attributes(params[:survey])
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to surveys_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.haml
= bootstrap_form_for @survey, :html => {:class => 'form-inline'} do |f|
  = f.text_field :name, :label => 'Survey Title'
  = f.fields_for :indicators do |i|
    .well{:id => "indicator#{i.object.id.to_s}"}
      = render 'indicators/fields', :f => i
      = link_to 'remove indicator', i.object, remote: true, method: :delete unless i.object.new_record?
      %hr
      = i.fields_for :answers do |a|
        %div{:id => "answer#{a.object.id.to_s}"}
          = render 'answers/fields', :f => a
          = link_to 'remove answer', a.object, method: :delete, remote: true unless a.object.new_record?
      - unless i.object.new_record?
        %hr
        = link_to 'add answer', new_answer_path(:indicator_id => i.object.id), remote: true
  - unless f.object.new_record?
    = link_to 'add indicator', new_indicator_path(:survey_id => f.object.id), remote: true
  = f.actions

app/views/surveys/edit.html.haml
.container
  .row
    .span4.offset4
      %h1 Editing survey

      = render 'form'

      = link_to 'Show', @survey
      \|
      = link_to 'Back', surveys_path

app/views/surveys/index.html.haml
%h1 Listing surveys

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @surveys.each do |survey|
    %tr
      %td= survey.name
      %td= link_to 'Show', survey
      %td= link_to 'Edit', edit_survey_path(survey)
      %td= link_to 'Destroy', survey, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Survey', new_survey_path

app/views/surveys/new.html.haml
.container
  .row
    .span4.offset4
      %h1 New survey

      = render 'form'

      = link_to 'Back', surveys_path

app/views/surveys/show.html.haml
.container-fluid
  .row-fluid
    .span12
      %h1= @survey.name

      %ol
        - for indicator in @survey.indicators
          %li
            = indicator.name
            %br
            = indicator.question
            %ul
              - for answer in indicator.answers
                %li= answer.content

      = link_to 'Edit', edit_survey_path(@survey)
      \|
      = link_to 'Back', surveys_path