config/routes.rb
JackAppBase::Application.routes.draw do
  resources :answers

  resources :indicators

  resources :surveys

  resources :sectors

  resources :sites

  resources :regions

  resources :sources

  devise_for :users

  root :to => 'statics#home'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #

    unless user
      user = User.new
      user.roles << Role.find_or_create_by_name('Public')
    end

    # can :read, Static

    if user.role? :admin
      can :manage, :all
    elsif user.role? :user
      
      # can :read, Static
      
      if user.role? :moderator
        can :manage, :all
        cannot :manage, [ User, Role ]
      end
    end

    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :content, :indicator_id

  belongs_to :question

  validates :content, :presence => true, :uniqueness => { :scope => :indicator_id, :message => 'Answers must be unique per indicator' }

end

app/models/indicator.rb
class Indicator < ActiveRecord::Base
  attr_accessible :name, :question, :survey_id, :answers_attributes

  belongs_to :survey

  has_many :answers, :dependent => :destroy

  accepts_nested_attributes_for :answers, :reject_if => proc { |a| a['content'].blank? }, :allow_destroy => true

  validates :name, :presence => true, :uniqueness => true
  validates :question, :presence => true, :uniqueness => true

end

app/models/region.rb
class Region < ActiveRecord::Base
  attr_accessible :name

  has_many :sources
  has_many :sites

  validates :name, :presence => true, :uniqueness => true

end

app/models/role.rb
class Role < ActiveRecord::Base

  validates :name, :presence => true

  has_and_belongs_to_many :users

end

app/models/sector.rb
class Sector < ActiveRecord::Base
  attr_accessible :name

  has_many :sources

  validates :name, :presence => true, :uniqueness => true

end

app/models/site.rb
class Site < ActiveRecord::Base
  attr_accessible :name, :region_id

  belongs_to :region

  has_many :sources

  validates :name, :presence => true, :uniqueness => { :scope => :region_id, :message => 'Site names must be unique within a region.' }

end

app/models/source.rb
class Source < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :phone, :region_id, :sector_id, :site_id

  belongs_to :region
  belongs_to :site
  belongs_to :sector

  validates :first_name, :region_id, :sector_id, :presence => true
  validates :email, :presence => true, :uniqueness => true
  validates :phone, :uniqueness => true

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  attr_accessible :name, :indicators_attributes

  has_many :indicators, :dependent => :destroy

  accepts_nested_attributes_for :indicators, :reject_if => proc { |a| a['name'].blank? }, :allow_destroy => true

  validates :name, :presence => true, :uniqueness => true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_and_belongs_to_many :roles
  accepts_nested_attributes_for :roles, :allow_destroy => true

  after_create :add_default_roles

  def role?(role)
    return !!self.roles.find_by_name(role.to_s.camelize)
  end

  private

  def add_default_roles
    self.roles << Role.find_or_create_by_name('User')
  end

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  load_and_authorize_resource

  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sites }
    end
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
    @site = Site.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @site }
    end
  end

  # GET /sites/new
  # GET /sites/new.json
  def new
    @site = Site.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @site }
    end
  end

  # GET /sites/1/edit
  def edit
    @site = Site.find(params[:id])
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(params[:site])

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render json: @site, status: :created, location: @site }
      else
        format.html { render action: "new" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sites/1
  # PUT /sites/1.json
  def update
    @site = Site.find(params[:id])

    respond_to do |format|
      if @site.update_attributes(params[:site])
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site = Site.find(params[:id])
    @site.destroy

    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/indicators_helper.rb
module IndicatorsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.haml
:erb
  <!DOCTYPE html>
%html
  %head
    %title Peace Corps Senegal | Food Security
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container-fluid
      .navbar.navbar-fixed-top
        .navbar-inner
          .container-fluid
            .row-fluid
              .span12
                %a.brand{:href => "#{root_path}"} PC|SN Food Security
                %ul.nav
                  %li.dropdown
                    %a.dropdown-toggle{'href' => '#', 'data-toggle' => 'dropdown'}
                      Go to
                      %b.caret
                    %ul.dropdown-menu
                      %li= link_to 'Surveys', surveys_path
                      %li= link_to 'Data Sources', sources_path
                      %li= link_to 'Regions', regions_path
                      %li= link_to 'Sectors', sectors_path
                      %li= link_to 'Sites', sites_path
                  %li.dropdown
                    %a.dropdown-toggle{'href' => '#', 'data-toggle' => 'dropdown'}
                      Add
                      %b.caret
                    %ul.dropdown-menu
                      %li= link_to 'Survey', new_survey_path
                      %li= link_to 'Source', new_source_path
                      %li= link_to 'Region', new_region_path
                      %li= link_to 'Sector', new_sector_path
                      %li= link_to 'Site', new_site_path
                %ul.nav.pull-right
                  %li= link_to 'Sign in', new_user_session_path unless user_signed_in?
                  %li= link_to 'Sign up', new_user_registration_path unless user_signed_in?
                  %li= link_to "Sign out #{current_user.email}", destroy_user_session_path, :method => :delete if user_signed_in?
    .container
      .row
        .span4.offset4
          - if notice
            .alert.alert-success.center
              = notice
          - if alert
            .alert.alert-error.center
              = alert
    = yield
    .container-fluid
      .row-fluid
        .span12
          %hr
          %p Peace Corps | Senegal Food Security Data - Developed by John F. Brown
    .container-fluid
      .row-fluid
        .span12
          - if Rails.env.development?
            .span12
              = debug(params)